version: 0.2

phases:
  pre_build:
    commands:
      - echo "This is prebuild phase"
      - echo $CODEBUILD_BUILD_NUMBER
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 381492254179.dkr.ecr.ap-south-1.amazonaws.com
  
  build:
    commands:
      - echo "This is build phase"
      - mvn clean install
      - ls -l target/
      - docker build . -t aws_spring:v$CODEBUILD_BUILD_NUMBER
      - docker images

  post_build:
    commands:
      - echo "This is post-build phase"
      - docker tag aws_spring:v$CODEBUILD_BUILD_NUMBER 381492254179.dkr.ecr.ap-south-1.amazonaws.com/aws_spring:v$CODEBUILD_BUILD_NUMBER
      - docker tag aws_spring:v$CODEBUILD_BUILD_NUMBER 381492254179.dkr.ecr.ap-south-1.amazonaws.com/aws_spring:latest
      - docker push 381492254179.dkr.ecr.ap-south-1.amazonaws.com/aws_spring:v$CODEBUILD_BUILD_NUMBER
      - docker push 381492254179.dkr.ecr.ap-south-1.amazonaws.com/aws_spring:latest
      - printf '[{"name":"aws_spring","imageUri":"%s"}]' 381492254179.dkr.ecr.ap-south-1.amazonaws.com/aws_spring:v$CODEBUILD_BUILD_NUMBER > imagedefinitions.json
      - cat imagedefinitions.json

  artifacts:
    files:
      - '**/*'



